Repository LearningChain/FrontEnd, pull requests merged in 2022-07, with the labels that each got.

#15 Feature/button
  client/.eslintrc.json
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/components/commons/Button/Button.stories.tsx
  client/src/components/commons/Button/Button.styles.ts
  client/src/components/commons/Button/Button.tsx
  client/yarn.lock
Labels: ⚙ CHORE, ✨ FEAT, 🎨 DESIGN

#19 feat : Checkbox 컴포넌트 생성
  client/src/components/commons/Checkbox/Checkbox.stories.tsx
  client/src/components/commons/Checkbox/Checkbox.styles.ts
  client/src/components/commons/Checkbox/Checkbox.tsx
  client/src/components/commons/Checkbox/Checkbox.types.ts
  client/src/components/commons/Checkbox/index.ts
Labels: ✨ FEAT, 🎨 DESIGN

#20 feat : Component Badge 제작
  client/.eslintrc.json
  client/src/components/commons/Badge/Badge.stories.tsx
  client/src/components/commons/Badge/Badge.styles.ts
  client/src/components/commons/Badge/Badge.tsx
  client/src/components/commons/Badge/index.ts
  client/yarn.lock
Labels: ⚙ CHORE, ✨ FEAT
