Repository LearningChain/FrontEnd, pull requests merged in 2022-09, with the labels that each got.

#101 feat: CommentInput 컴포넌트 제작
  client/src/components/commons/Input/Input.stories.tsx
  client/src/components/commons/Input/Input.styles.ts
  client/src/components/commons/Input/Input.tsx
  client/src/components/layouts/ContentCardList/ContentCardList.styles.ts
  client/src/components/patterns/CommentInput/CommentInput.stories.tsx
  client/src/components/patterns/CommentInput/CommentInput.styles.ts
  client/src/components/patterns/CommentInput/CommentInput.tsx
  client/src/components/patterns/CommentInput/index.ts
  client/src/components/patterns/InfoCard/InfoCard.styles.ts
Labels: ✨ FEAT, 🎨 DESIGN

#105 feat : StudyDetailLink Patterns 제작
  client/src/_shared/icons/basic.tsx
  client/src/components/patterns/StudyDetail/StudyDetail.styles.ts
  client/src/components/patterns/StudyDetail/StudyDetail.tsx
  client/src/components/patterns/StudyDetailLink/StudyDetailLink.stories.tsx
  client/src/components/patterns/StudyDetailLink/StudyDetailLink.styles.ts
  client/src/components/patterns/StudyDetailLink/StudyDetailLink.tsx
  client/src/components/patterns/StudyDetailLink/index.ts
Labels: ✨ FEAT, 🎨 DESIGN

#110 feat: Selector 개발
  client/src/_shared/colors/colors.tsx
  client/src/_shared/colors/index.ts
  client/src/_shared/index.ts
  client/src/_shared/shadows/index.ts
  client/src/_shared/shadows/shadows.tsx
  client/src/_shared/typography/fontFamily.tsx
  client/src/_shared/typography/fontSize.tsx
  client/src/_shared/typography/fontWeight.tsx
  client/src/_shared/typography/index.ts
  client/src/_shared/typography/lineHeight.tsx
  client/src/components/commons/Input/index.ts
  client/src/components/commons/Selector/Selector.stories.tsx
  client/src/components/commons/Selector/Selector.styles.ts
  client/src/components/commons/Selector/Selector.tsx
  client/src/components/layouts/RewardGrid/RewardGrid.stories.tsx
  client/src/components/layouts/RewardGrid/RewardGrid.tsx
  client/src/components/patterns/CalendarBox/index.ts
  client/src/components/patterns/CommentInput/CommentInput.tsx
Labels: ✨ FEAT, 🎨 DESIGN

#111 design: SidebarItem에 Checkbox 추가
  client/src/components/commons/Checkbox/index.ts
  client/src/components/commons/SideBarItem/SideBarItem.tsx
Labels: 🎨 DESIGN

#113 feat : ContentReviewList 추가 및 관련 컴포넌트 수정
  client/package-lock.json
  client/package.json
  client/src/components/commons/Button/Button.styles.ts
  client/src/components/patterns/Review/Review.stories.tsx
  client/src/components/patterns/Review/Review.styles.ts
  client/src/components/patterns/Review/Review.tsx
  client/src/components/patterns/ReviewAnswer/ReviewAnswer.stories.tsx
  client/src/components/patterns/ReviewAnswer/ReviewAnswer.styles.ts
  client/src/components/patterns/ReviewAnswer/ReviewAnswer.tsx
  client/src/containers/ContentPage/ContentReviewList/ContentReviewList.stories.tsx
  client/src/containers/ContentPage/ContentReviewList/ContentReviewList.styles.ts
  client/src/containers/ContentPage/ContentReviewList/ContentReviewList.tsx
  client/src/containers/ContentPage/ContentReviewList/index.ts
  client/yarn.lock
Labels: ✨ FEAT
